<?php

namespace system\modules\categories\controllers;

use system\core\Controller;
use system\core\View;
use system\core\Modules;

class CategoryController extends Controller {

    public $vars=[];
    public static $html_actions = [
        'default',
    ];

    public function __construct($route) {
        parent::__construct($route);
        $this->model=$this->loadModel('Category');
    }

    public function loadModel($name) {
        $path = 'system\modules\categories\models\\'.ucfirst($name);
        if (class_exists($path)) {
            return new $path;
        }
    }

    public function defaultAction() {
        $vars = [
            'module' => 'categories',
            'section_tpl' => 'category',
            'data' => $this->route['data'],
            //'cats' => $this->model->list()['data'] ?? [],
            'cats' => $this->model->cats(),
            'files' => $this->model->files(),
            'translates' => $this->model->translates(),
        ];
        return $this->view->renderBlock($vars);
    }

    public function getEditView()
    {
        //return parent::getEditView(); // TODO: Change the autogenerated stub
        ob_start();
        require __DIR__.'/../templates/edit_category.php';
        $content = ob_get_clean();
        return $content;
    }
}